// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1615191817);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1615191937);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1615247015);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1615191697);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1615192057);
user_pref("browser.cache.disk.capacity", 634880);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "IR");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Thu, 25 Feb 2021 01:53:01 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1615191818);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"8c4cffa5-755b-46fd-9774-40fcb00cae9e\",\"default-theme@mozilla.org\":\"921216a2-009b-4f52-83dc-88588d49de58\",\"google@search.mozilla.org\":\"e1ffc156-a6de-4ff8-a05d-1beeea0e19d9\",\"amazondotcom@search.mozilla.org\":\"602b5487-c63d-4ce3-bc56-d0dd080eac5b\",\"bing@search.mozilla.org\":\"86bdcc84-049d-440a-94c6-5656cc7535b5\",\"ddg@search.mozilla.org\":\"58aea4f2-3aac-4c01-bbd5-e12aae7c1809\",\"twitter@search.mozilla.org\":\"3ad79d94-12bc-4e01-a255-647491fd90c6\",\"wikipedia@search.mozilla.org\":\"d7e460d8-a63e-4fd4-aab5-5831ea9be6a5\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1615192592);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "ba7647e6-3f27-4712-8268-299093465a3");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("places.database.lastMaintenance", 1615192592);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("security.sandbox.plugin.tempDirSuffix", "2e72d774-baa7-4a6b-8502-98926ab97488");
user_pref("services.blocklist.pinning.checked", 1615191698);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1615190270428\"");
user_pref("services.settings.last_update_seconds", 1615191698);
user_pref("services.settings.main.hijack-blocklists.last_check", 1615191698);
user_pref("services.settings.main.language-dictionaries.last_check", 1615191698);
user_pref("services.settings.main.sites-classification.last_check", 1615191698);
user_pref("services.settings.security.onecrl.checked", 1615191698);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1615192592);
user_pref("toolkit.telemetry.cachedClientID", "e3c84d62-acfe-4c45-a6c9-365b50b402c3");
user_pref("toolkit.telemetry.prompted", 2);
